### PR TITLE
Fix dynamic bitcode

### PR DESCRIPTION
**Pull request by nicph**
These changes embed the bitcode in the resulting framework, and also checks the presence of the __LLVM section.

I wasn't able to re-open the PR #1.

### CODE REVIEW

**Comment by keeshux** [comment]
You could have pushed to the same branch and the PR would have included the new commit automaticall. Thanks again!

**Comment by keeshux** [comment]
@nicph sorry if I reset the branch abruptly, but the script still has a few issues. I'll keep you posted.

**Comment by nicph** [comment]
My bad, i didn't test the 'static' generation since i added `pipefail`. 
The issue is due to `grep -q` that stops reading and closes `stdin` on the first match, and `objdump` doesn't seem to support it.
I fixed this in my fork (keeping `pipefail`), i can open a PR if you're interested.

**Comment by keeshux** [comment]
@nicph good point, fixed in `master` already. I think we can close this PR conversation. Thanks for your support!

**Pull request merged**
